{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether.clickhouse.fullname" . }}
  namespace: {{ include "aether.namespace" . }}
  labels:
    {{- include "aether.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: tcp
      port: 9000
      targetPort: tcp
  selector:
    clickhouse.altinity.com/chi: {{ include "aether.clickhouse.fullname" . }}
{{- end }}
